### ISSUE TITLE
[RDF]Ahn'kahet: The Old Kingdom

### ISSUE THREAD

**Issue by kalitarq** [WoWManiaUK/Redemption#1009]
Me and my party got to the last boss of Ahn'kahet: The Old Kingdom Herald Volazj and we began the encounter.We were doing fine until the boss started casting Insanity making the Twisted Visages.Those visages killed me a paladin and our tank in less than a second or as they say one shot us.Here is an image of damage recount,
![wowscrnshot_032717_181646](https://cloud.githubusercontent.com/assets/26717836/24364326/168d6ad0-131b-11e7-849b-261d4e7c67ae.jpg)

**Comment by wowgamer1980** [comment]
That's true we all have problem killing the Visages. They do insane damage killing everyone.

**Comment by elagen** [comment]
From what i have noticed from the boss that the Npc that should spawn from the insanity phase should spawn where the players are standing instead of spawning at the boss 

in the video the adds hit for around 200-300 per hit and this is normal 
https://www.youtube.com/watch?v=7rGiqUQwPUY&t=27s

As you can see in this video from Normal i am taking 800-1000 damage per hit - with all 5 players stacked together it is a pure kill to who ever the 5 mobs hit
https://drive.google.com/open?id=0B_GODmkO59aEVHNKWHpuWEZGUms

as you can see on Heroic the damage that is given is 300-500
https://www.youtube.com/watch?v=DnQcc3VNctw

As you can see here on the server with the adds i am taking damage from 3000-6000 with a crit
https://drive.google.com/open?id=0B_GODmkO59aEeGlFNXc1Rmhwc0k

this needs to be adjusted

**Comment by fvicaria** [comment]
This should be fixed in dev. Please confirm.

**Comment by Plege** [comment]
![grafik](https://cloud.githubusercontent.com/assets/24266043/24402743/3074b10c-13ba-11e7-8cde-3b6a1a38d5aa.png)

i still get git for 4 k in heroic and the spirita appears at the bosses location rather than mine

**Comment by Emcitementz** [comment]
> should spawn where the players are standing
Coming soon too.

**Comment by Emcitementz** [comment]
> should spawn where the players are standing

Coming soon too.

**Comment by Emcitementz** [comment]
> should spawn where the players are standing

Fixed.
