### ISSUE TITLE
[Quest] Valkyrion Must Burn

### ISSUE THREAD

**Issue by StarrZappa11** [WoWManiaUK/Redemption#1375]
Unable to enter the harpoon to burn the hay stacks. Picture's attached but doesn't show much. My cursor doesn't change from the hand to the green arrow. Please help.

![image](https://user-images.githubusercontent.com/29348748/28044793-72b46b18-65a7-11e7-9513-5550ca111983.png)

**Comment by StarrZappa11** [comment]
this is not fixed.

**Comment by StarrZappa11** [comment]
Hey Janitor,


This quest is still not working for me, still unable to access the harpoon.



-----Original Message-----

**Comment by fvicaria** [comment]
Checking it now. It was working on dev just now.

**Comment by fvicaria** [comment]
Just tried and it works. You need to find which cannon works for you. It will be random. There are 4.

**Comment by fvicaria** [comment]
There was indeed an issue. Once you dismount the cannon cannot be used again. I have fixed it but it will probably need restart.

**Comment by StarrZappa11** [comment]
Still can't take control of any of the four harpoons :\ I wasn't sure what you meant by needs a restart so I downloaded a new launcher and that didn't work either. 

Thank you for all of your help.
