### ISSUE TITLE
[Quest] Nexus-Prince Shaffar's Personal Chamber

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#1565]
Hello! There should be 2 ethereum prisons inside Mana-Tombs heroic. One in the 2nd room (the place showed in the screenshot below) and second one in the last chamber. Unfortunately both are missing so 3 quests in one chain cannot be completed: http://www.wow-mania.com/armory/?quest=10977, http://www.wow-mania.com/armory/?quest=10981 and http://www.wow-mania.com/armory/?quest=10982.

![obrazek](https://user-images.githubusercontent.com/30184491/30003780-5b1f6862-90c3-11e7-9bb7-14ec59e9040c.png)

**Comment by captainloozer** [comment]
Hell Cathyr1, and thank you for your report.

I can confirm that in heroic mana tombs, even while on the quest, the Stasis Chambers are not present, which prevents the player from continuing the mentioned quest lines. Blow is an image from wow-head that shows what the chamber looks like and where it should be, and also a screen I took in game on dev of it not being there on heroic mode.
![181971-stasis-chambers-of-the-mana-tombs](https://user-images.githubusercontent.com/9828794/30004362-5e8c559e-9093-11e7-8c64-c16f2d66a238.jpg)

![image](https://user-images.githubusercontent.com/9828794/30004357-56345680-9093-11e7-829e-03645280e53c.png)

The object ID is http://www.wow-mania.com/armory/?object=185519

The chamber in Nexus-Prince Shaffar's room is also missing.

Below is a picture of where it should be and where I am shown on dev of it not being there.

![image](https://user-images.githubusercontent.com/9828794/30004400-20f14e50-9094-11e7-87c7-efaf09d2284c.png)

![image](https://user-images.githubusercontent.com/9828794/30004396-0f871ac8-9094-11e7-8b89-33f382aa7260.png)

**Comment by captainloozer** [comment]
@fvicaria 

I've found another Github post, Issue 7 on that list seems to be exactly what's going on.  There may be more information valuable to you there.

https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/2350

**Comment by fvicaria** [comment]
Fixed in dev.

**Comment by captainloozer** [comment]
The first stasis chamber was there when I came in the dungeon while on the quest http://www.wow-mania.com/armory/?quest=10977

However, after leaving, turning in the quest, then coming back, it was no longer there.  Resetting the instance didn't make it reappear.  I assume this is because I am not on the quest anymore.

The second chamber is also missing.  If this is because I am not on a quest to open it, that may be the problem.  There is a repeatable quest to turn in a Mark of the Nexus King, which gives you the key to open Shaffar's Stasis chamber. http://www.wowhead.com/item=32079/shaffars-stasis-chamber-key

To my knowledge, there is no quest to open Shaffar's Stasis chamber, it just allows you to fight an optional boss for extra loot.

**Comment by fvicaria** [comment]
It has a timer you have to reset dungeon

**Comment by captainloozer** [comment]
As of now, both stasis chambers are showing up but Shaffar's chamber does not summon Yor like it is supposed to.  When opening Shaffar's stasis chamber with The Eye of Haramad (Item ID 32092), it does nothing.

**Comment by captainloozer** [comment]
After discovering that both chambers were only showing up on normal mode, it is now fixed where both chambers will show up on Heroic mode.  However, Shaffar's stasis chamber is now incorrectly requiring the Mana-Tombs stasis chamber key (ID 32069) where it should require Shaffar's Stasis Chamber key (ID 32079) or The Eye of Haramad (ID 32092) to open.

![image](https://user-images.githubusercontent.com/9828794/30063009-bc2020ca-9212-11e7-9873-ef171bf3ced8.png)

**Comment by captainloozer** [comment]
After using the mana-tombs stasis chamber key, Yor was summoned as intended and able to be killed for extra loot.  This part is working.

![image](https://user-images.githubusercontent.com/9828794/30063140-3da90706-9213-11e7-955b-745abb80b75d.png)

**Comment by fvicaria** [comment]
Fixed that too.

**Comment by captainloozer** [comment]
Confirmed fixed in dev.

**Comment by cathyr1** [comment]
Thanks much for your job on this bug. Just one special question. I have the first quest http://www.wow-mania.com/armory/?quest=10977 already completed from the past. So now when I enter Mana-Tombs heroic I wanna obtain quest http://www.wow-mania.com/armory/?quest=10981 in order to finish this chain but I won´t be able to open this stasis chamber cause I´m missing Mana-Tombs Stasis Chamber Key without possibility to obtain it. How can I solve this? Can I ask for this item in in-game ticket?

**Comment by cathyr1** [comment]
Hello. I now checked you have added a Shaffar Stasis chamber to 2nd room but still I haven´t found the first  (basic) stasis chamber in that is npc that gives this quest. So I still cannot obtain a quest and a key.

**Comment by fvicaria** [comment]
![image](https://user-images.githubusercontent.com/9414661/30123585-70c229f2-932a-11e7-9a64-27a969cfa439.png)
![image](https://user-images.githubusercontent.com/9414661/30123622-8bf7f9ea-932a-11e7-9aaa-7f7e56726856.png)

**Comment by cathyr1** [comment]
I already deleted my previous post, I found both stasis chambers at last. Still has a problem that cannot obtain second quest from this chain cause I cannot open the first chamber as I have the first one already completed. So I made a ticket where ask for this item: http://www.wow-mania.com/armory/?item=32069 without that I cannot continue :(

**Comment by fvicaria** [comment]
You get when you get the quest: http://www.wow-mania.com/armory/?quest=10977

**Comment by cathyr1** [comment]
I know that but I have this quest already completed. Did it long time ago so I can no longer obtain this key and thus cannot open stasis chamber and obtain a next one.

**Comment by fvicaria** [comment]
I can give it to you. WHat is the char name?

**Comment by cathyr1** [comment]
I have a problem. GM Saints now contacted me ingame and gives me this first quest http://www.wow-mania.com/armory/?quest=10977 together with a key once more. But when I opened that stasis chamber I haven´t found there the right NPC. So I headed to Blade Edge and return him this quest there. However he did not give me the continue http://www.wow-mania.com/armory/?quest=10981. So can I please ask you to give me this quest and contact me in-game? My name is Rakhwa, horde side. Thanks a lot.

**Comment by cathyr1** [comment]
So I have succesfully killed Yor (image as a proof) but the NPC don´t give me the last quest http://www.wow-mania.com/armory/?quest=10982. So can you please give me also this quest? I am exalted at consortium so I can obtain it. Thanks a lot. 
![obrazek](https://user-images.githubusercontent.com/30184491/30125485-ccfd39ba-9338-11e7-9b55-25f369c35a39.png)
![obr 2](https://user-images.githubusercontent.com/30184491/30125519-e9890050-9338-11e7-8e74-7b2b543740e9.png)

**Comment by fvicaria** [comment]
Something got messed up in your char.
Ask a GM to give you the quest.

**Comment by cathyr1** [comment]
OK done now. Thanks much for your help with this issue and quests.
