### ISSUE TITLE
[Quest] Now This is Ram Racing... Almost. 

### ISSUE THREAD

**Issue by redhawk816** [WoWManiaUK/Redemption#1646]
http://www.wowhead.com/quest=11318/now-this-is-ram-racing-almost
Objectives are not completing.   I maintained each of the speeds for over the 8 seconds that are needed.  None of the objectives completed so neither did the quest.

**Comment by GmSaintz** [comment]
I can confirm the issue with this quest.

**Comment by goldstinger** [comment]
Also confirming. After 8 seconds with the same speed buff, the quest objective for any of the objectives do not complete.

**Comment by redhawk816** [comment]
This affects two other quests that I cant think of, both daily quests: http://www.wowhead.com/quest=11412/there-and-back-again and The Bark quests such as http://www.wowhead.com/quest=11408/bark-for-tchalis-voodoo-brewery

**Comment by Karlusdark** [comment]
Also confirming this issue, it's been like this since last year

**Comment by fvicaria** [comment]
Are you getting the credit for the various stages?

**Comment by squalllh1989** [comment]
none of the 3 stages work, after maintain 1 min for each state, quest didn't complete for any state.

**Comment by goldstinger** [comment]
To address @fvicaria in particular, no. The credit for the various stages are not given after 8 seconds, or after any amount of time in those stages.

**Comment by Hulkster-WowMania** [comment]
Confirmed fixed in dev.  All three speeds give credit.  

https://youtu.be/2W98dO1sz1k

**Comment by Ukhozii** [comment]
The problem remains, at least on Horde's side. I've done all 3 different stages well over 8 sec and I never get any of the speeds completed. A friend of mine has also tried it and it just doesn't work for us.

**Comment by Karlusdark** [comment]
Issue remains on Alliance's side, done all 3 stages over 8 sec and nothing happened.

**Comment by squalllh1989** [comment]
Guy, it's "Fixed on Dev", the fix isn't pushed to redemtion yet, wait for the next update
