### ISSUE TITLE
[Quest] The Killing Time

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#1695]
I have problems with quest http://www.wow-mania.com/armory/?quest=13371. No portal appeared in Stormwind when obtained it so I´ve flied to the place personally but no NPCs there. So the final step http://www.wow-mania.com/armory/?quest=13377 cannot start for me.
![obrazek](https://user-images.githubusercontent.com/30184491/31047668-0ac2bf3e-a60f-11e7-963d-69372a9c0ba9.png)

**Comment by cathyr1** [comment]
Ah, I´m sorry (#1227). Just that one is from May and still not work. So should I ask GM´s ingame for the help with both quests?

**Comment by fvicaria** [comment]
Please search before posting a new issue.
Duplicate #1227

**Comment by cathyr1** [comment]
I know about that one, posted it in my previous comment. But this issue is solved so long so I wanna know how to do the quest now.

**Comment by fvicaria** [comment]
The quest is not solved. It is still an open issue.
You can complete it yourself since it is officially in the bug list.
type: .bq 13371

**Comment by cathyr1** [comment]
When I typed this, there was an error speech: "BQ Error: Invalid quest status. Do you have it in the quest log?" In fact, I need to return this quest to the NPC, obtain the new one http://www.wow-mania.com/armory/?quest=13377, then mark this one as completed and at last return it to Varian.

**Comment by fvicaria** [comment]
Ask a GM to complete for you.

**Comment by cathyr1** [comment]
Ok, I´ve made a ticket. Thanks for your advice.
