### ISSUE TITLE
[Spell] Intense cold

### ISSUE THREAD

**Issue by squalllh1989** [WoWManiaUK/Redemption#1979]
[This spell](http://www.wowhead.com/spell=48094/intense-cold) is used by [Keristrasza](http://www.wowhead.com/npc=26723/keristrasza), the last boss of [The Nexus]([url](http://www.wowhead.com/the-nexus)).
- What should happen: the spell stack on any body that stand still, the more stack they have, the more damage they took. It damage should be very low at first, then rise with number of stack, and become unhealable later if party member don't move arround to remove it.
- What is happening: Intense cold is doing 13k damage each tick with only 1-2 stack, this make the boss become extreamly hard to fight, as she can cast [Crystal Chains](http://www.wowhead.com/spell=50997/crystal-chains) to prevent everyone in the party to move. So at least the damage must be healable with everyone in the party have like 5 stacks. Currently, after engage, Keristrasza cast  Crystal Chains, then after 2-3 sec, at least haft of the raid die to 2 tick of intense cold, which shouldn't happen.

**Comment by fvicaria** [comment]
Can you give me any info that shows that this is wrong or that the damage is too high? Where do you base your analysis from?

**Comment by fvicaria** [comment]
Also, I have a slightly different version in dev now. Can you test it?

**Comment by Dranah** [comment]
It appears so that the DOT does normal damage (2-3k tick) until Crystallize (the freeze) is cast, then the rooted targets take 12k damage ticks afterwards. For whatever reason the main tank wasn't affected, possibly because she had no stacks when Crystallize was cast and the subsequent stacks weren't bugging out , only the ones already present at the Crystallize cast.
Here's video proof and this is definitely wrong: https://www.youtube.com/watch?v=etWyiAOgqXE&feature=youtu.be

**Comment by VA-L** [comment]
- When players will enter in the instance, Keristrasza will now be already frozen.
- Jumping while having the **Intense Cold** aura will now remove it correctly.
- Fixed the damages of the **Intense Cold** stacks.

**Comment by squalllh1989** [comment]
Not fixed yet, i just try it and getting 3k+ damage from 1 stack of  Intense Cold

**Comment by squalllh1989** [comment]
To be easier to look, i modify the hp of the test char and use recount to see the damage it take, here is the screen shot:
![wowscrnshot_122417_120801](https://user-images.githubusercontent.com/27235989/34324363-1faba7cc-e8a3-11e7-85c4-c8aab4b28570.jpg)
So as you can see, the damage Intense Cold doing is now:
**-3286 for first tick (1 stack)**
**-17204 for 2nd tick (2 stack)** => amazing, this can kill me already, as i got only 21k hp as a nearly full bis mage, so basicly i must keep my stack at 1 or i'm gonna die
**-17204 for 3nd tick (3 stack)**
**-49498 for 4nd tick (4 stack)** => this can almost kill every tank, it already reach the level of the lich king's enraged hit in icc normal
**-49498 for 5nd tick (5 stack)**
**-87856 for 6nd tick (6 stack)** well, beside the tank, everyone else should just die now :v

And those damage are completely diffrent from what it say in the tooltip:
![wowscrnshot_122417_121159](https://user-images.githubusercontent.com/27235989/34324399-1d54cec6-e8a4-11e7-8547-08175ab2331f.jpg)
The tooltip here was of a 1 stack, it say 100 damage everyone sec

**Comment by VA-L** [comment]
Made some changes, can it be tested again ?

**Comment by squalllh1989** [comment]
Confirmed that Intense cold is now back to doing normal damage tick again. Also, since you are having a look at this, can you look at the "Intense cold" achivement also please ? I have like 9 stack of intense cold when kill  Keristrasza, and still had the achivement, it's like a free give away while it should be much harder to get

**Comment by VA-L** [comment]
> can you look at the "Intense cold" achivement also please ? I have like 9 stack of intense cold when kill Keristrasza, and still had the achivement, it's like a free give away while it should be much harder to get

- The achievement will no longer be given if you had more than 2 stacks when killing Keristrasza.

Up to test **in the morning/afternoon**.

**Comment by squalllh1989** [comment]
Confirmed, the The achievement now will only be given if you had below 2 stack. Thank you very much, The nexus is all good now.
