### ISSUE TITLE
[Boss] Thorim-Ulduar

### ISSUE THREAD

**Issue by Bartok14** [WoWManiaUK/Redemption#2101]
This fight worked really well although we weren't able to down it as we had people that had to leave after a few attempts I'll update on any bugs I notice next time we attempt this. There was however a bug with the initial encounter.

1) The first time you enter the room all the adds inside the arena are essentially not doing anything and are just siting in place. Not really and issue just a visual bug for the initial pull similar to the tomes on Hodir during the first encounter. The second part is that Sif is nowhere to be seen within the room and may confuse anyone that is attempting to do Thorim on hard mode. Also upon completing the hallway in the first attempt there doesn't appear to be any dialogue between Thorim and Sif (we did it in under three minutes), which may cause the first attempt to fail at doing the hardmode if there is a trigger that is supposed to happen which makes it doable, perhaps you might want to test this. Good thing we wiped the first time because the hallway group forgot to jump off the platform :) 

The rest of the fight seemed to work without any issue, and we had two very nice attempts on it although we wiped to some mechanics we are still getting used to. I will try to update this the next time we attempt to do it if I notice anything else. I hope you understand that when I made the initial suggestion post on the forums that I was simply trying to give people an alternative way to get one of their Best in Slot items. I also understand that in using Github you want all the issues separate in different topics but since this is the first week I'm just going to lump them together by bosses. If you have any feedback on how you want me to report any of the issues in the future let me know you can also send me a letter in game. Also just to appease my curiosity is there anyway for you to post updates on when we might expect the next patch to come out and patch notes that explain what was fixed. I haven't been on the server that long only about 4-5 months so any feedback on this question would be appreciated. 
I will be trying to get my guild to continue our run of Ulduar in hardmode this week and will post anything that I notice, there were a few things with the leviathan, and Ignis but I'll wait to confirm them at a later date. Anyways I hope you appreciate the effort I tried to put in on these posts and hope you can work out the kinks in the future. Thanks!

**Comment by fvicaria** [comment]
When were this boss and the other issues you entered done?

**Comment by Bartok14** [comment]
They were done today. I started this morning with a random raid and did the weekly quest. I then got my guild together and started working on the hard modes. We were running these approximately from 12 am server time to about 6 am server time. Why would you close all of them? I was instructed to post the issues that I found on Github by Janitor.

**Comment by Dranah** [comment]
Update: Sif now properly appears when the last mob of the beginning event is slain and thorim encounter is engaged. Upon making it on time for hard mode, she starts attacking the raid as intended and teleports down afterwards, spamming blizzards on you. Yell conversations between Sif and Thorim works as well
Remaining problems: You can engage the mobs in the beginning separately, aggroing the worm does not aggro the other mobs, aggroing the warrior mobs still leaves the acolyte out of combat
The lever that opens the door for the gauntlet has a 10seconds cast-time to activate, which i doubt is intended, as far as I remember doing this on retail, it should be instant

**Comment by Keader** [comment]
@Dranah what's the real issue here?
What happens and what should happens? can you organize?

**Comment by Dranah** [comment]
Yeah sorry if it wasn't clear.

Bug 1 - visual issue - 
How it works atm:  There's a worm and a group of humanoids staring at each other and not doing anything. 
How it should work: The group of humanoid mobs should look like they're fighting off the worm until they're engaged.

Bug2 - pull issue - 
How it works atm: You can aggro and kill the worm separately using a ranged attack, then the melee adds and then the acolyte in the back, because attacking one mob does not aggro the rest.
How it should work:  and when you touch any of the mobs in the room, all of them engage and you're fighting the worm and the entire humanoid group together.

**Comment by Dranah** [comment]
There seems to be another issue which is still under testing.
Thorim's summon Lightning orb http://www.wow-mania.com/armory/?spell=62391 appears to blow off sometimes without the criteria being triggered.

How it should work: Thorim should use this when there are no players in the arena and/or when 5minutes have passed after the lever became active and no players have engaged him yet.
How it works right now: on the first attempt (of the day, of the week?! this is unclear) it appears to fire immediately as the lever becomes active, a raid progressing through the gauntlet with decent speed would meet it halfway to Thorim, being wiped. This is regardless of the criteria (players in arena/5mins passed). Bug cannot be reproduced for the subsequent attempts on the same day.

**Comment by Dranah** [comment]
Update:
1. NPCs in the beginning can be still killed separately, they do not aggro together, though they should.
2. Their visual is still broken on the first attempt, but after a wipe it gets fixed and for the subsequent attempts the worm and the humans will look like they attack each other. (this is minor issue and only bugged on the first pull)
3. Small mobs in the gauntlet (http://www.wow-mania.com/armory/?npc=32874) are now completely useless, as in they can be attacked but not aggroed, they ignore you. You can damage them but they reset back to 100% hp immediately. Only the two big golems work properly. (This is a HUGE problem)
4. Furthermore, attacking any of the small mobs (http://www.wow-mania.com/armory/?npc=32874) in the "Clash of Thunder" (first corridor of the gauntlet), seems to trigger Thorim to fire "Summon lightning orb" http://www.wow-mania.com/armory/?spell=62391 and wipe the raid. (This is also very bad)

**Comment by Dranah** [comment]
Update: 
Gauntlet now works fine, lightning orb doesn't trigger randomly.
Problem: Upon defeating Thorim, he does his speech n all, teleports away but no loot chest is awarded.

**Comment by Keader** [comment]
@Dranah can you test now if works?

**Comment by Dranah** [comment]
yes it works now, fixed

**Comment by Dranah** [comment]
New problem arose:

The Lever to open gauntlet door can be activated before pulling or killing the set of starter mobs that engage Thorim.
This means, since the gauntlet mobs are inactive before the encounter is engaged, that the gauntlet team can get a head start and run up to the first Colossus before the encounter and timers are even started.

**Comment by wow-mania** [comment]
Is this a new or regression?

**Comment by Keader** [comment]
Fixed.

**Comment by Dranah** [comment]
Indeed.

**Comment by Dranah** [comment]
This problem is back. I don't know how or why.
Lever is active before you even engage the mobs in arena, let alone kill them.

**Comment by wow-mania** [comment]
@Keader can you check if something got reversed or missed.
