### ISSUE TITLE
[Spell] Vesperon's Twilight Torment (Obsidian Sanctum)

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2103]
Hello,
I'd like to report Vesperon's (http://www.wowhead.com/npc=30449) Twilight Torment (http://www.wowhead.com/spell=58835/twilight-torment) for stacking to 10-13 instead of applying just one stack.
This debuff appears when Vesperon's twilight portal is up and is supposed to cause 75% increased fire and shadow damage as well as cause shadow damage to raid members when they attack. 
How it works at the moment: when Vesperon's portal appears, the whole raid receives 10-13 stacks of the aforementioned debuff, increasing shadow and fire damage taken by 800-1000% varying on how many stacks you get. As soon as you land a damaging attack, the shadow damage it gives you with so much increase will do at least 20-30k damage and oneshot you. Your only chance to kill Vesperon at the moment is to burst him down before his portal appears.
Note, i've tested this so far on 10man only.

**Comment by TheManiax** [comment]
The debuff is fixed on Dev
But if you get into portal, there is no way back

**Comment by Dranah** [comment]
I re tested this and found the following:

The spell stacks multiply with the amount of targets present. When testing alone, you get the debuff with one stack as intended, when testing with 4 characters, every one received 4 stacks.
Here's the screenshot: https://imgur.com/9FFFbDc

Furthermore, it does not only stack for players, on 25player mode, I received 34 stacks on each character, which counted most likely for the 5 permanent pets and a couple of bloodworms present.

**Comment by Dranah** [comment]
issue still persists

**Comment by fvicaria** [comment]
How do you know? You have just told me you need a raid with 25 people.
I have just fixed.

**Comment by fvicaria** [comment]
Unless you did what you told me please leave the fixed.

**Comment by Dranah** [comment]
https://imgur.com/Xwr3NtJ

10/10 raid still receives 10 stacks instead of one, removing Fixed label.

**Comment by TheManiax** [comment]
Twilight torment 57935 doesn't go higher than one stack at all

**Comment by Dranah** [comment]
Update:
- Spell grants only 1 stack at once to each raid member now (fixed)
- Spell does not stack as intended when Vesperon recasts his portal/acolyte (needs fix)
- Debuff sometimes expires on the Main tank for unknown reasons (it should not have a duration)
- When the main tank loses the debuff, the next portal/acolyte spawn will be able to recast it, giving a 2nd stack to the raid, and reapplying the first to the main tank
- The 1second internal cooldown on the self- Shadow damage triggered by the debuff is not present, allowing the damage to strike a player multiple times within one second

**Comment by squalllh1989** [comment]
My bad the stack which instant kill people should not be a tweaking problem

**Comment by VA-L** [comment]
- When players leave the instance, they'll loose the debuff if they had it.
- Debuff now has a 1sec internal CD.
- Debuff now correctly stack.
- Debuff will be recasted whether the tank has the aura or not (just like it should).

Up to test.

**Comment by Dranah** [comment]
Works as intended now.

**Comment by Dranah** [comment]
This bug has just returned like I have no bloody idea when or how. It worked fine like until 1-2 weeks ago.

**Comment by fvicaria** [comment]
Absolutely nothing changed here in weeks.

**Comment by Dranah** [comment]
Fixed again.
