### ISSUE TITLE
[Mage - Arcane] Missile Barrage only triggering about 20-25% instead of 40%

### ISSUE THREAD

**Issue by justincormier** [WoWManiaUK/Redemption#2125]
Several arcane mages were noticing that the Missile Barrage buff was not triggering as often as it should, and DPS was drastically reduced. The talent sets the trigger rate at 40%, but after testing Arcane Blast over the course of two days on training dummies, I got the following trigger rates:

1/18/18
Arcane Blast Casts: 300
Missile Barrage Triggers: 66
Missile Barrage Trigger Rate: 22%

1/19/18
Arcane Blast Casts: 200
Missile Barrage Triggers: 48
Missile Barrage Trigger Rate: 24%

Casting Arcane Blast 4x in a raid provided an Missile Barrage roughly 95% of the time. Running multiple heroics yesterday and today, it was triggering maybe once out of every two to three Arcane Blast stacks of 4.

**Comment by Keader** [comment]
Hmm Was working Very well in dev.
I Will take a look again

**Comment by fvicaria** [comment]
@Keader can you check if the code is still there? :)

**Comment by fvicaria** [comment]
This is fixed in dev. It was deployed today.

**Comment by Keader** [comment]
Let me know if you reproduce this issue after deployed and i will review @justincormier ^^

**Comment by Alickszander** [comment]
It seems this is still not working as intended on live mania (mania patch 2.2.0).  Proc rate still feels lower than usual and it has been a point of discussion in worldchat for the past 30 minutes.

**Comment by fvicaria** [comment]
@Keader can you re-check this please.

**Comment by Keader** [comment]
Do you have account in Dev server @Alickszander ?

**Comment by Alickszander** [comment]
I do not Keader

**Comment by Keader** [comment]
I will make more tests with @TheManiax tomorrow. 😸

**Comment by Magabro** [comment]
Missile Barrage Expected Proc Rate = 40%
Number of Arcane Blast Casts = 200
Missile Barrage Procs = 99
Proc Rate Observed = 49.5%

**Comment by philoudu16** [comment]
Has this been pushed to redemption yet?
I just gave it a try on redemption and got 62 procs/214 casts so under 30%

**Comment by philoudu16** [comment]
Feel free to contact me if u want to test things out too (ingame name Zunrin)

**Comment by Keader** [comment]
Ok, core part fixed.
I need some tester to test it with me :)

**Comment by philoudu16** [comment]
I can if you want :) you can contact me in game (char name is Zunrin)
