### ISSUE TITLE
[Quest] Mounting Up (ID 12141)

### ISSUE THREAD

**Issue by patrickhousley** [WoWManiaUK/Redemption#2161]
Quest: http://www.wowhead.com/quest=12414/mounting-up

After using the carrot on the stick, you are able to ride the horse toward the camp for a few seconds. Eventually the horse will begin walking back to its spawn location and will continue walking it's path. I have tried multiple horses and I cannot get any of them back to the camp.

**Comment by TheManiax** [comment]
http://www.wowhead.com/item=37708/stick
http://www.wowhead.com/object=189983/wild-carrot
http://www.wowhead.com/npc=26472/highland-mustang

**Comment by Magabro** [comment]
I had this issue while leveling up but this only effects the horses in the big herd that roam.  If you pick a horse that is alone outside the herd it will work

**Comment by Magabro** [comment]
Just tested on Dev and have some more info.

It appears that any horse with scripted movements will interrupt your run back and attempt to execute their movement script.  There is 1 black mustang that has no scripted movement and can be ridden back to the turn in.  
![wowscrnshot_012718_145809](https://user-images.githubusercontent.com/34353250/35477208-660a788e-0373-11e8-82f2-4c0a62e4f00d.jpg)

**Comment by fvicaria** [comment]
Quest works with the horses that are standing still. I will try to make it work for all.

**Comment by fvicaria** [comment]
I tested this and it was fixed.

**Comment by Magabro** [comment]
Tested again just now.  Halfway working for me on Dev.  The horses in the big herds running around can be returned, but the stand alone horses with scripted movement still cannot be returned.

**Comment by TheManiax** [comment]
@Magabro @WhitephoenixTheBunny 
You can test [Into the Realm of Shadows](http://www.wowhead.com/quest=12687/into-the-realm-of-shadows) & [A Mammoth Undertaking](http://www.wowhead.com/quest=12607/a-mammoth-undertaking) to make sure about the fix as well.
They are all effected with the same code.
There are probably more **Riding Quests** effected as well.
Feel free to check them if you are aware of any.
