### ISSUE TITLE
[Boss] Runemaster Molgeim

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2698]
https://www.wowhead.com/npc=32927

Bug compilation for Assembly of Iron:

1) Shield of runes
https://www.wowhead.com/spell=63489
https://www.wowhead.com/spell=63967

How it should work:
Runemaster Molgeim casts spell=63489, which is a shield absorbing damage. IF this shield is broken by players doing damage, he gains the other buff, spell=63967, which is a 50% damage boost.
If the effect is dispelled before it is broken, the boss does NOT gain the damage buff.
If a mage spellsteals the effect, he gains the absorb shield spell=63489 and when he takes damage, and the shield is broken, the mage gains the damage boost effect  spell = 63967

How it works atm:
Boss gains the shield spell=63489 and no matter what you do, damage, dispel, spellsteal or let it expire when the effect is gone, the boss gains the 50% damage boost from spell=63967.

2) EDIT: My bad this is intended. 

3) https://www.wowhead.com/spell=62273/rune-of-summoning
"Rune of Summoning" fails to spawn adds on 25man mode. The boss casts it but the rune does not appear and no adds come out.
https://www.wowhead.com/npc=32958/lightning-elemental these adds should spawn
Note, this ability works fine on 10.man

4) Achiev "Can't do that while stunned" https://www.wowhead.com/achievement=2948
https://www.wowhead.com/npc=32857/stormcaller-brundir
Not so much Runemaster's problem but oh well.
Is awarded regardless of completing criteria on 25man.
It should require the raid to interrupt EVERY chain lightning, and whirls before a single tick is let out.

**Comment by Keader** [comment]
Drop of Archivum Data Disc is correct.
Should drop of  Steelbreaker and Molgeim (https://www.wowhead.com/item=45506/archivum-data-disc)

**Comment by Dranah** [comment]
UPDATE:
- Shield of Runes now work as intended.
- Rune of Summoning is now no longer cast by the boss on 25man at all. Sometimes he does an emote with no spell following, possibly he attempts to cast it but something blocks (need fix)
- Achievement "Cant do that while stunned" is still awarded regardless of completing criteria, moreover, it doesn't even require you to defeat the whole council, I got it mid-fight after killing just Steelbreaker.

**Comment by Keader** [comment]
Done

**Comment by Dranah** [comment]
UPDATE:

- Missing casts issue still persists, for some reason every second rune of death or rune of summoning is skipped, the emote goes out but the spell cast does not
- "Can't do that while stunned" is now not working at all, even when you complete the criteria...

**Comment by Keader** [comment]
Janitor not full build xd

**Comment by Keader** [comment]
Try now xD

**Comment by Keader** [comment]
Missing casts fixed.

**Comment by Dranah** [comment]
The fight flipped out upon pull and crashed the PTR. Might want to look into this @wow-mania

**Comment by Dranah** [comment]
All works good now.
