### ISSUE TITLE
[Spell] Glyph of Life Tap

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2806]
http://www.wow-mania.com/armory/?spell=63321

This is a buff gained from the glyph http://www.wow-mania.com/armory/?item=45785 that grants you 20% of your spirit as spell power after using Life Tap.
It mostly works as intended, except it has a glitch with switching talent builds.
When you change spec, the glyph effect won't work until you relog.

Steps to repro:

1) have dual talent spec
2) switch from your whatever off spec to the build which has Glyph of Life tap
3) use life tap, there is no buff gained
4) relog, Life tap, it works again

This is extremely annoying as you have to relog everytime you change build to make the glyph work again.

**Comment by Keader** [comment]
fixed

**Comment by Dranah** [comment]
Glyph of Life tap no longer needs relog to work after switching talents.

**Comment by Ashamedlol** [comment]
Still broken and forces you to relog, at least from what I experienced on ally toons.

**Comment by Keader** [comment]
Did you tested in ptr?
Possible that janitor forgot to send do redemption

**Comment by Ashamedlol** [comment]
Thought it was pushed live since it was closed half a week ago.
And ptr is sometimes down :P.

**Comment by wow-mania** [comment]
@Keader let me know if there was a sql missing to be applied

**Comment by Keader** [comment]
i will check in my laptop when i got home @wow-mania

**Comment by Keader** [comment]
Fix sended again.
Closing.
