### ISSUE TITLE
[Dungeon] UpperBRS Warchief Rend Blackhand

### ISSUE THREAD

**Issue by GMSunShield** [WoWManiaUK/Redemption#319]
[Dungeon] Upper Blackrock Spire  http://www.wow-mania.com/armory/?achievement=1307

[Boss]: Warchief Rend Blackhand http://www.wow-mania.com/armory/?npc=10429#summoned-by

[Room/Boss Event]: When you enter the room to start the boss fight Lord Victor Nefarius and Warshief rend blackhand will start yelling emotes, This will start a event. A Door in the room https://s18.postimg.org/wv2dkq3ax/UBRScloseddoor.jpg will then start to open and summon adds players have to kill the adds be for the door opens again https://s18.postimg.org/sczw6am2x/UBRSOpendoor.jpg
The  #door will open 3 times and spawn 3 packs of dragon adds. After you have killed everything Warchief Rend Blackhand will then come down in to that same room the adds came from and get on his dragon (mount http://www.wowhead.com/npc=10339/gyth ). The door will then open again he will come out. Players have to get the mount down to 15% hp then Warchief Rend Blackhand will dismount and start fighting as well players then have to kill the dragon and the boss. After Warchief Rend Blackhand dies Lord Victor Nefarius will yell and all Doors to the room will open allowing players to do the rest of the Dungeon and go to Raid: BWL 

> [Issue1] The door https://s18.postimg.org/wv2dkq3ax/UBRScloseddoor.jpg only spawn one group of adds at the start they should open 3 times and spawn 3 packs of adds. 
> 
> [Issue2] When your attacking the bosses (mount http://www.wowhead.com/npc=10339/gyth ) and get it to 15% hp Warchief Rend Blackhand will dismount and die be for he hits the ground this bugs the event and the boss fight never ends this Locks players in the room. They will have to hearth or make a ticket
> 
> Boss fight when bugged https://youtu.be/PS1XiOD5Sak

**Comment by wow-mania** [comment]
Fixed for next Wednesday. Tested by @GMSunShield  already.

**Comment by Calebrimbor** [comment]
Status on BugTracker set as 'Fixed'.

**Comment by GMBoomboom** [comment]
Players are still experiencing issues with the door not opening or the boss despawning or being untargetable
