### ISSUE TITLE
T8 DK Set from the Mall gives no Stats

### ISSUE THREAD

**Issue by Zytor** [WoWManiaUK/Redemption#3355]
**What is Happening:**
My T8 set from the Mall gives no stats, only Armor and the stats through my gems.
It is also not only a visual bug on the item, i also get no stats in my character info and the damage i do with the gear is the same as without the gear on.

Screenshots of the bug:

![WoWScrnShot_062019_234716](https://user-images.githubusercontent.com/52062478/59900746-690b5180-93f9-11e9-905c-0a5d581758ef.jpg)
![WoWScrnShot_062019_234719](https://user-images.githubusercontent.com/52062478/59900747-69a3e800-93f9-11e9-8a25-7915cafdd898.jpg)
![WoWScrnShot_062019_234721](https://user-images.githubusercontent.com/52062478/59900748-69a3e800-93f9-11e9-93fa-c6fb79ef8bc5.jpg)
![WoWScrnShot_062019_234724](https://user-images.githubusercontent.com/52062478/59900750-69a3e800-93f9-11e9-9e96-dfc1acd57d9e.jpg)
![WoWScrnShot_062019_234726](https://user-images.githubusercontent.com/52062478/59900751-69a3e800-93f9-11e9-9df5-ea0c3012afd6.jpg)
![WoWScrnShot_062119_075320](https://user-images.githubusercontent.com/52062478/59900843-abcd2980-93f9-11e9-8b36-ecf32cfec9ef.jpg)

**Comment by wow-mania** [comment]
Your set should be items: 46111, 46113, 46115, 46116, 46117
If not open a ticket and we change for you.

**Comment by Zytor** [comment]
How or where can I see the item numbers?

**Comment by WhitephoenixTheBunny** [comment]
Tested it, purchased both sets on T8 seller at mall. And DPS gear doesn't have stats the Items ID's are 46111, 46113, 46115, 46116, 46117

example:
![image](https://user-images.githubusercontent.com/31921098/59907307-b4762d80-9402-11e9-9053-cf5236bb9b34.png)

**Comment by WhitephoenixTheBunny** [comment]
Something went wrong on #3350
I haven't checked the stats on that one.

**Comment by wow-mania** [comment]
will re-check

**Comment by wow-mania** [comment]
Fixed on dev and applied to live but needs restart and player needs to delete cache to see it.

**Comment by Zytor** [comment]
I deleted the cache but the set is still the same. Should this be solved or is it in process?
