### ISSUE TITLE
[Quest] Ancient Spirit

### ISSUE THREAD

**Issue by IvanLlanas** [WoWManiaUK/Redemption#3500]
[Flute of the Ancients] (http://www.wow-mania.com/armory/?item=11445)
Arei (http://www.wow-mania.com/armory/?npc=9598)
[Ancient Spirit] (http://www.wow-mania.com/armory/?quest=4261)

After using the [Flute of the Ancients], Arei spawns and he gives the [Ancient Spirit] quest, in which I have to escort him to "Safety".
On arriving to 49.6,14.9 (Irontree Woods, Felwood) a lot of elemental trees spawn around us and attack us. We killed them and another three spawn. We killed them and another three spawn. An so on. After killing literally hundreds of them and trying some not working kite tricks realized that every time Arel gets back to its escort path a new set of elementals spawns.

I, finally, thought that maybe the target of the quest is Arel dying there. I left Arel on its own, and, of course died, and the quest failed.
I couldn't find a video with this quest resolution, so I don't know what should have happened.

**Comment by WhitephoenixTheBunny** [comment]
![image](https://user-images.githubusercontent.com/31921098/63431619-283eb180-c417-11e9-9bb3-b1cea7386ec7.png)
Done without issues.
Try relog / delete cache and retry the quest.

**Comment by IvanLlanas** [comment]
Cache deleted.
Addons removed, all of them.
And still the same:
![WoWScrnShot_082119_164329_](https://user-images.githubusercontent.com/25532326/63442343-3d293e00-c433-11e9-9b95-033881d84fee.jpg)

**Comment by WhitephoenixTheBunny** [comment]
Open a ticket ingame. A GM may help you with other solutions

**Comment by IvanLlanas** [comment]
I opened the ticket and did a few tests and tries the GM suggested me. They didn't work. The GM had to force the success of the quest in the quest log. In the live realm the quest seems to be (somewhat) bugged.
