### ISSUE TITLE
[Spell/NPC] Burning Pitch

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3653]
https://www.wowhead.com/spell=71335/burning-pitch
used by https://www.wowhead.com/npc=36969/skybreaker-rifleman
or https://www.wowhead.com/npc=36968/korkron-axethrower
Part of the Gunship battle encounter.

**How it works atm:** 
1. Every time a new rifleman/axethrower add spawns on the enemy ship, they cast burning pitch as their first ability before they would begin shooting at players. Even if you stun them and interrupt their cast, they will attempt to recast it afterwards.
2. Every time the players on your own ship are positioned in the back or center of the ship instead of being very close to the riflemen on the edge, the Riflemen will again begin to cast Burning Pitch instead of shooting your raid.
This deals a ton of unintended damage to your own ship no matter how well you handle the fight.

**How it should work:** 
1.Burning Pitch is an enrage mechanic that only should be cast if there are no players left behind on your own ship and therefore the riflemen/axethrowers have no target to pick up for shooting so they go ham on your ship.
2.The shoot/axe throw attacks have (or should have) infinite (50000yrds) range so it should not matter where your players are positioned on the ship as long as someone is there, the riflemen should be shooting them instead of burning your ship.

**Comment by Keader** [comment]
ok, what? @Dranah 

"1.Burning Pitch is an enrage mechanic that only should be cast if there are no players left behind on your own ship and therefore the riflemen/axethrowers have no target to pick up for shooting so they go ham on your ship."

Can you explain better? is very confuse to me.

**Comment by Dranah** [comment]
Ok so, the Riflemen/axethrowers are by default shooting at players that are on your own ship. They pick up targets only on your own ship, ignore targets on the enemy ship.
If they cannot find any targets to shoot at, because you left your own ship empty (everyone went to the enemy ship, or your defense group died), then they begin using Burning Pitch which destroys the ship with siege damage at a much faster rate.

However here, they also cast burning pitch once when they spawn, regardless of players being present for them to shoot at. Instead of immediately beginning to shoot at players on your own ship, they cast a burning pitch and only pick up a target to shoot after.
This leads to a lot of unintended burning pitches going off and those few pitches do a shitload more damage to your ship than the rockets which normally slowly damage it.

**Comment by Dranah** [comment]
Ok the fight broke.
1) The riflemen no longer shoot burning pitch on spawn and if you are in long range at the back of the ship which is good (fixed)
2) However, they also don't shoot burning pitch if there is someone inside a Cannon on your own ship (being in a cannon should not qualify as being on your ship). This needs fixing.
3) The Mortar guys stopped shooting rockets, and the mage is not spawning on time, i don't know how these got fucked up, they weren't a part of the report.

Overall, this needs to be reverted ASAP because you can probably solo the fight sitting in cannons now.

**Comment by Keader** [comment]
Fixed cannon stuff
and fixed mortar, mortar is new issue, not caused by me.

**Comment by Dranah** [comment]
Okay, I finally found what's bugging the mortars.

So, the issue with Burning Pitch being cast even with players on your own ship is fixed.
However, the Riflemen/Mortars still can't pick up a target if those players are in the center of the ship rather than on the edge and now they simply won't cast anything if there are no players on the edge.

How it should work: The Riflemen/Mortar guys have 50000yrd (infinite) range, it should be able to shoot arrows and artillery anywhere on the enemy ship.
