### ISSUE TITLE
[Dungeon] Pattern drop rate in ToC/ToGC too low

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#3782]
**Links:**
e.g. Item https://www.wowhead.com/item=47623/plans-saronite-swordbreakers

**What is Happening:**
The drop rate of all the crafted patterns in ToC/ToGC is much too low - there is hardly ever a pattern drop in the past year.
Whilst Wowhead drop rates should be taken with a pinch of salt, the era-appropriate comments on wowhead and gamepedia seems 1 pattern/run was reasonably common. 1.5% seen on wowhead would equate to roughly 1 pattern/month if 10/25 run.

There seems to be a similar discussion about this on TC, where the drop rate was eventually increased from 1 to 6:
https://github.com/TrinityCore/TrinityCore/issues/13042

**What Should happen:**
Drop rate of patterns in TC (for both bosses and cache) should be raised (in 10/25 and nm/HC) such that 1 pattern can reasonably be expected to drop in a month assuming both 10/25 are completed.
Although there is no stated results from TC, suggest replicating the change that was made in TC here.

**Comment by wow-mania** [comment]
As-is.

**Comment by Dranah** [comment]
This is not okay to be left as-is. These patterns are basically non-existant on the server, it's impossible to find a crafter when a new character tries to gear up, I see people spam world chat for weeks to find any of them and have to pay above 2k gold tip just to even have a chance.

We have been fixing the overabundant drop rates of other BOE epics that helped newbies gear up, it is not balanced to leave this broken.

**Comment by Kitzunu** [comment]
test now
changed chance on npc id:
34566, 35216, 35268, 35269, 35347, 35348, 35349, 35350, 35351, 35352, 35447, 35448, 35449, 35615, 35616

**Comment by Dranah** [comment]
There is no change. With 1% chance for each pattern you should receive at least 4-5 patterns out of 200 kills, considering there are like 10+ of them.
Not a single drop. I have a feeling that extra loot table is just not working at all.

**Comment by Kitzunu** [comment]
I and Dranah is checking to get a good number on this

**Comment by wow-mania** [comment]
If this cannot be solved we just close as-is. I can see no big issue with some extra loot.

**Comment by Kitzunu** [comment]
it is important recipes.
it's quite a big deal

**Comment by Dranah** [comment]
Someone gotta find why the recipes aren't dropping at all. Whatever kitzu sets the drop to, its zero actual drop, so tweaking that number won't help. 
This is a critical issue, every single TOGC recipe is missing from the game atm.

**Comment by Dranah** [comment]
Leaving it as-is is not an option, the only acceptable workaround would be to move them from the "extra loot" table to the regular one, so they would drop in place of 1 other item when they do. That is not blizzlike, but closer to it than the current state.

**Comment by Dranah** [comment]
Update: after my last test session what I can tell is that when a recipe would drop based on its drop chance, you see the loot icon remain active on the corpse after you looted it. Indicating there is some loot there, but you cannot see it. Feels like something is blocking players from being able to see the loot, which is why the drop is virtually 0.

**Comment by wow-mania** [comment]
Maybe a condition?

**Comment by Kitzunu** [comment]
I have checked for conditions but could not find any. Perhaps I search wrong.. or could it be something in the core script for togc?

**Comment by Rushor** [comment]
yep it has conditions

select * FROM `conditions` WHERE sourcegroup=35352

**Comment by Rushor** [comment]
https://i.imgur.com/IS6tA6V.jpg
https://i.imgur.com/hqCB2tR.jpg

tada. the chance was like 1 %.

horde and alli loot is different. have set it to 10 percent on kill for both factions now.

**Comment by Dranah** [comment]
1 percent is correct. It was just not dropping by that 1% of cases either at all :dagger: 
10% is way too fucking high

**Comment by Dranah** [comment]
Oh okay so its 10% total for the 18 patterns. This is okay then, even too small. Each pattern should have an individual chance of 1% so the total chance for extra loot should be 18%, which then divides equally among the 18 patterns.

**Comment by Rushor** [comment]
yes they are all in groups.

actually almost all big raid boss loot is in groups so

f.ex:

10 % chance for lootgroup Z to drop 1 item

lootgroup Z contains item h, j, u,i,k,l,t,p, etc.

**Comment by Rushor** [comment]
increased to 18 percent now.

**Comment by Rushor** [comment]
and i gues that it the way it should work. blizz always adds recipes in lootgroups. so only one recipe per kill on boss

**Comment by wow-mania** [comment]
Fixed applied to live.

**Comment by Oganku** [comment]
This fix has made those patterns drop more reliably, but I have noticed 2 issues remaining with them.

1. For some reason, only the blacksmithing plans can drop on 10 man heroic difficulty, and their respective drop rate is higher to compensate for the smaller amount of patterns in the 18% chance pool.
See below for the boss loot tables of each boss on 10hc, where plans have 3% chance to drop, but leatherworking or tailoring patterns are missing:
https://www.wow-mania.com/armory/?npc=34797#drops-2
https://www.wow-mania.com/armory/?npc=34780#drops-2
https://www.wow-mania.com/armory/?object=195633
https://www.wow-mania.com/armory/?npc=34496#drops-2 and https://www.wow-mania.com/armory/?npc=34497#drops-2
https://www.wow-mania.com/armory/?npc=34564#drops-2


2. The drop rate of the patterns/plans from the Champions' Cache (loot for the Faction Champions fight) is still extremely low (1% for the entire 18 patterns instead of 1% each). The chance for them to drop is individually 0.06% instead of 1%, or about 16 times too low. This also applies to the issue listed above, making the plans drop with 0.17% chance (3 times higher) on 10 heroic only.

https://www.wow-mania.com/armory/?object=195632 (25 man normal)
https://www.wow-mania.com/armory/?object=195633 (10 man heroic)
https://www.wow-mania.com/armory/?object=195635 (25 man heroic)

@Rushor Fix that was applied last year is perfect, just need to expand it to the chest and make sure the patterns are also included on 10 heroic.

**Comment by Rushor** [comment]
1.) the chests will now drop leather, tailor, blackmsith recipes in 10 hc, 25 hc, 25 nh for 1 percent each
2.) the 10 hc boss versions will drop the  leather, tailor, blackmsith recipes  for 1 percent each

**Comment by Rushor** [comment]
fixed once ptr is up again

**Comment by Rushor** [comment]
Oh and not a Regression in this case since we have Not talked about chests before
