### ISSUE TITLE
[NPC] Lurielle appearing to offer quests - 24117 - Howling Fjord

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Redemption#4058]
**Links:**
NPC: https://www.wow-mania.com/armory/?npc=24117

**What is Happening:**
Lurielle is showing ! even when no quest is available.
![image](https://user-images.githubusercontent.com/46089380/73102660-42128200-3eea-11ea-8e50-c02b1ad68acf.png)

**What Should happen:**
Lurielle should not show ! if no quest is available.

**Comment by Kitzunu** [comment]
I have fixed it, but have not sent to PTR yet since I am not at my main PC.

Will update you when it is there :)

**Comment by Kitzunu** [comment]
maybe 1 hour or so

**Comment by Kitzunu** [comment]
Fixed

**Comment by jarvik76** [comment]
While the ! has gone from over her head, she still shows the ! on mouseover, instead of the speech bubble mark.

**Comment by Kitzunu** [comment]
> KitzunuToday at 11:21 PM
that's nothing that can be done
try deleting cache
but we can only hide the one over her head
