### ISSUE TITLE
[Quest] Researching the Corruption - can't be turned it

### ISSUE THREAD

**Issue by Eleera** [WoWManiaUK/Redemption#4194]
Hi, 

Quest "Researching the Corruption", give by Gershala Nightwhisper in Auberdine can not be turned in. The required items for the quest are obtainable, but when I return to the NPC, there is no "yellow question mark" above his head. The quest is logged as "complete" in my log, but it is not possible to talk to the NPC.

I have talked to a GM in-game who tried re-spawning the npc, but that didn't solve the issue. Said GM advised me to open a ticket on your forum so, yeah. Here it is (:

Might it be possible for this issue to be fixed? It's silly to this, since the abundance of quests in the game, but for completing certain achievements it might be handy if this quest were completable.

Kind regards

N.

Link to quest on wowhead: https://classic.wowhead.com/quest=1275/researching-the-corruption

**What Should happen:**

**Comment by wow-mania** [comment]
Pretty sure you miss some requirements.
The fact that the quest is obtainable does not imply that you can talk to another NPC of another faction

**Comment by Eleera** [comment]
> Pretty sure you miss some requirements.
> The fact that the quest is obtainable does not imply that you can talk to another NPC of another faction

It is a quest which requires to collect items. I have the correct amount of the correct items in my inventory. I travel to the location marked on my map where the quest-giver is located. 


Normally when a quest is in process, but not yet complete, a grey mark is above the NPC. Even that is missing. The NPC is also of the same faction. Same race, even.

**Comment by Rushor** [comment]
fixed the questmarks to be shown again https://i.imgur.com/eXVfKEa.jpg

Quest can be rewarded again.

**Comment by Eleera** [comment]
I hate to be this person, but I am afraid it still doesn't work for me. I tried downloading the launcher again, but that didn't solve it either.

**Comment by Rushor** [comment]
no, the fix will be applied with the next update. prolly on thuesday

**Comment by Eleera** [comment]
> no, the fix will be applied with the next update. prolly on thuesday

Aaaaaah of course!! Thanks!! :D

**Comment by GMMetaxa** [comment]
On a sidenote: Quests that demand an "Items delivery" do bug when a player has multiple of those quests in their questlog. Deleting the quests and completing one by one is not a fix, but a way to continue.

**Comment by Rushor** [comment]
No that does Not help in this case. The Bug was different :)

**Comment by jarvik76** [comment]
@Rushor ok I understand the fix now.  However, if we fix it that way, the conditional dependency in https://www.wow-mania.com/armory/?quest=3765 should be removed.
i.e. this:
![image](https://user-images.githubusercontent.com/46089380/76248299-f9fcb400-6238-11ea-846e-70cdf6b5b1c7.png)
Otherwise you are effectively removing one of the Loremaster-available quests.

**Comment by jarvik76** [comment]
Thanks @Rushor for removing dependency, works ok now.
