### ISSUE TITLE
[Mechanic] Feign Death vs oozes from Professor Putricide

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4224]
**Links:** https://www.youtube.com/watch?v=A4m8A7U-enQ (03:10-03:25 explained); 
https://www.youtube.com/watch?v=MyXBFH0jm1s (at 04:25 you can see it in action, it's a bit messy with POV but if you look at it you'll see that the ooze targeting hunter stopped while still alive, while hunter is still alive - visible on the grid.)

**What is Happening:** When targeted by the ooze, Feign Death does not cancel the ooze chasing the hunter but ignores it and continues to blow up on contact.

**What Should happen:** Once Feign Death is used, the ooze should stop moving and select new target.

**Comment by WhitephoenixTheBunny** [comment]
I believe this is as inteed, @Keader ?

**Comment by Keader** [comment]
Fixed.

**Comment by bLeyaa** [comment]
@Keader @Rushor 
On live server the behavior is still the same as before.

**Comment by bLeyaa** [comment]
Still doesn't work on live.

**Comment by Keader** [comment]
Please confirm if is working or not in PTR.

**Comment by bLeyaa** [comment]
![WoWScrnShot_040220_183344](https://user-images.githubusercontent.com/61625377/78274456-8b95d380-7510-11ea-964b-6d007afce004.jpg)

Same happens with the green ooze.

**Comment by bLeyaa** [comment]
Not part of the change with old core, the above issue still exists.

**Comment by Keader** [comment]
where's my video dear? :)

**Comment by Rushor** [comment]
it may just needs reapply then?

**Comment by bLeyaa** [comment]
@Keader 

Orange: https://youtu.be/4EiV0zsH9YY

Green: https://youtu.be/oLZBc9ocEX8

**Comment by Keader** [comment]
Try now

**Comment by bLeyaa** [comment]
Works fine now.
Thanks @bluemonstrr @Keader
