### ISSUE TITLE
[Quest/NPC] Summoned NPCs spawn in double

### ISSUE THREAD

**Issue by Guigou4261** [WoWManiaUK/Redemption#4703]
**Links:**
https://wotlkdb.com/?quest=11788
https://wotlkdb.com/?quest=10111
https://wotlkdb.com/?quest=9427
https://wotlkdb.com/?quest=10585
https://wotlkdb.com/?quest=611

**What is Happening:**
I noticed that when a quest requires you to use an item/interact with someting in order to summon a monster and kill it, said monster appears in double. This can be quite a challenge. Especially when said monster is an elite for a group quest.
I have listed above a few examples of quest in which such event occured.

**What Should happen:**
The Npc should appear in only 1 copy

**Comment by jeyrella** [comment]
Hmm.  @Rushor this appears to be confirmed.  Reeks of the same problem we had in AN on ticket
https://youtu.be/cnJdWl1eVu4
https://youtu.be/r6Ly6jZuitg
https://youtu.be/w9ZUQ-9Zstw

Any ideas on what we changed recently that could cause this.  Definitely regression going on here.

**Comment by Rushor** [comment]
Is new issue, will try to fix all at once

**Comment by Rushor** [comment]
ALL fixed, over 3000 events where affacted.

basically every entry was just 2 times there - removed the duplicate for all. just inspect some quests if they are still fine.

**Comment by kamoodle5** [comment]
Discovered two more instances where duplicate NPC's appear upon summon.

The Blackhood Corrupted (https://wotlkdb.com/?quest=4763)
Cat Figurine (https://wotlkdb.com/?object=13359)

The cat figurine has a chance to summon a ghost saber cat, but upon success, two cats spawn instead of one.

**Comment by Rushor** [comment]
All fixed yes

**Comment by jeyrella** [comment]
Fixed.
https://youtu.be/VrWcrdBxQ2k
https://youtu.be/Uv5do79N8Ew

**Comment by Rushor** [comment]
Bosses and all Kind of item and quest stuff was affected by this, all Around the world

**Comment by Guigou4261** [comment]
I believe it is not entirely fixed
https://imgur.com/a/uXdBagL (screenshot)
https://wotlkdb.com/?quest=12569 (quest)

**Comment by Rushor** [comment]
the fix will be applied on thuesday
