### ISSUE TITLE
[Quest] Wintergrasp Weeklies

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4881]
**Links:** https://www.wowhead.com/quest=13195
https://www.wow-mania.com/armory/?quest=13156
https://www.wow-mania.com/armory/?quest=13154
https://www.wow-mania.com/armory/?quest=13153

**What is Happening:** The 4 "elemental" weekly quests in Wintegrasp are currently locking each other once one has been taken. Each quest has 4 versions, 2 horde and 2 alliance (1 for when you control the fortress and 1 for when you don't). 

It is only possible to complete 1 of the 4 right now. You are able to see all 4 quests at their respective quest givers, but once you accept any of them, the other 3 will lock and become unavailable, which shouldn't happen. 

**What Should happen:** As indicated on the armory, taking one of the weeklies should only lock yourself from taking the other version of the same quest for your faction. 

This results in 4 elemental weeklies being available to do each week.

*I know this is related to a previous issue, but I'm not sure which #, so I opened a fresh one.

**Also small detail, the wrong Sorceress Kaylana was removed with the fix for #4804 , leaving her little tent empty, and the remaining sorceress standing alone in the wrong place. Removing the current one and putting back the one that was wrongly removed before would fix it.

**Comment by Oganku** [comment]
The one near the red tent. Only the one near the blue tent should be there. Alliance don't see the red tent when they hold wg anyways. 

![image](https://user-images.githubusercontent.com/34783736/90987129-9c45f500-e556-11ea-9629-917e3a35c458.png)
It looks silly with her standing alone in the corner.

**Comment by Rushor** [comment]
thw wrong one is replaced by an alliance guard now. only the one in the tent stays

**Comment by Oganku** [comment]
Sorceress fix is good, quests still lock each other out for no reason. Can see all 4 initially, then I accept one and the other just become unavailable when they shouldn't.

**Comment by Rushor** [comment]
exlusive groups removed - you should be abel to take all 4 now

**Comment by jeyrella** [comment]
A lot of this is still an issue.   The quests are indeed fixed when each faction holds the fortress, but there are interaction problems when the opposite faction holds WG.

There is still an interaction between quests.
Bones and Arrows
Warding the Warriors
on Alliance questgivers when WG is held by Horde
https://youtu.be/8KcLL_IES04

Seigemaster Stouthandle is once again not offering Fueling the Demolishers but only when Horde hold WG
![image](https://user-images.githubusercontent.com/46089380/91106558-e4eed280-e66a-11ea-9646-539096b65212.png)


On the Horde side, when Alliance hold, all of the quests are still interacting between each other.
https://youtu.be/SDZCz--bmWw


Sorceress fix is not correct;  
when Horde hold she is now in the tent inside the fortress as well as in her tent at the FP (she should not be in the fortress when WG is held by Horde), and is offering the quest.
![image](https://user-images.githubusercontent.com/46089380/91106467-a0fbcd80-e66a-11ea-8304-2e8354984550.png)

When Alliance hold she is now in her tent in at the FP (she should only be in the fortress)
![image](https://user-images.githubusercontent.com/46089380/91107345-fa64fc00-e66c-11ea-9ef6-f078a590466c.png)

**Comment by Rushor** [comment]
There is a lot of condition that need to be checked here

**Comment by Rushor** [comment]
I have to delay that fix for this week

**Comment by Sarahbear85** [comment]
0

**Comment by Sarahbear85** [comment]
As horde warrior there are some quests that do not show active at the NPC (Fueling the Demolishers, Bones and Arrows, and Jinxing the Walls)

There were also a few quests that show active at the NPC and can be accepted, but after completed the quests cannot be turned in. (A Rare Herb, Defend the Siege and Warding the Warriors)

If you need anymore information, please let me know!

**Comment by Rushor** [comment]
> Bones and Arrows
Warding the Warriors
on Alliance questgivers when WG is held by Horde

this should be fixed now

**Comment by Rushor** [comment]
>Sorceress fix is not correct;
when Horde hold she is now in the tent inside the fortress as well as in her tent at the FP (she should not be in the fortress when WG is held by Horde), and is offering the quest.

fixed aswell. 2 incorrect spawns are removed now. if alliance owns the battle Sorceress will spawn inside in the tent, and if alliance fails Sorceress will spawn outside (no more double spawn there aswell)

**Comment by Rushor** [comment]
>There were also a few quests that show active at the NPC and can be accepted, but after completed the quests cannot be turned in. (A Rare Herb, Defend the Siege and Warding the Warriors)

some of the quests depend on each other - so if one is done - the other can no longer be done

**Comment by Rushor** [comment]
>Seigemaster Stouthandle is once again not offering Fueling the Demolishers but only when Horde hold WG

should also be fixed now

**Comment by Oganku** [comment]
Here is what's still missing for Alliance Side:

- [ ] Alliance elemental weeklies for attacking and defending are missing their exclusivity. It's currently possible to pick up both versions of the quest each week. The following twin quests should therefore all lock the player from taking/completing its counterpart:

- [ ] A Rare Herb

https://www.wow-mania.com/armory/?quest=13156 (Defender)
https://www.wow-mania.com/armory/?quest=13195 (Attacker)

- [ ] Bones and Arrows

https://www.wow-mania.com/armory/?quest=13154 (Defender)
https://www.wow-mania.com/armory/?quest=13196 (Attacker)

The defender version of Fueling the Demolishers (Alliance), is missing from Siege Master Stouthandle when Alliance holds the fortress. Horde do have access to both their versions however. Need to also make sure both versions are exclusive to each other.

- [ ] Fueling the Demolishers

https://www.wow-mania.com/armory/?quest=236 (Defender)
https://www.wow-mania.com/armory/?quest=13197 (Attacker)

- [ ] Warding the Warriors

https://www.wow-mania.com/armory/?quest=13153 (Defender)
https://www.wow-mania.com/armory/?quest=13198 (Attacker)

- [ ] Also, Commander Zanneth that gives the quest No Mercy for the Merciless is always spawned inside the fort, regardless of who controls it. 

![image](https://user-images.githubusercontent.com/34783736/92509682-a283d480-f1d8-11ea-8f64-74a712d85582.png)
The version of him at the graveyard that should give the attacker version https://www.wow-mania.com/armory/?quest=13179 is missing altogether. 

Both versions should be mutually exclusive:
https://www.wow-mania.com/armory/?quest=13177 (Defender)
https://www.wow-mania.com/armory/?quest=13179 (Attacker)

**Comment by Oganku** [comment]
And for Horde:

- [ ] The 3 Defender following elemental quests currently lock out each other while they should not:

https://www.wow-mania.com/armory/?quest=13194 (Defender - Healing with Roses)
https://www.wow-mania.com/armory/?quest=13191 (Defender - Fueling the Demolishers)
https://www.wow-mania.com/armory/?quest=13192 (Defender - Warding the Walls)

- [ ] All 3 of those should only lock out their attacker counter part in the following pairs : 

Healing with Roses
https://www.wow-mania.com/armory/?quest=13194 (Defender)
https://www.wow-mania.com/armory/?quest=13201 (Attacker)

Fueling the Demolishers
https://www.wow-mania.com/armory/?quest=13191 (Defender)
https://www.wow-mania.com/armory/?quest=13200 (Attacker)

Warding/Jinxing the Walls
https://www.wow-mania.com/armory/?quest=13192 (Defender)
https://www.wow-mania.com/armory/?quest=13202 (Attacker)

Bones and Arrows is currently only available on its Attacker version and is completely missing from Lieutenant Vieron Blazefeather inside the fort when Horde controls it. Both below should be mutually exclusive.

https://www.wow-mania.com/armory/?quest=13193 (Defender) **MISSING**
https://www.wow-mania.com/armory/?quest=13199 (Attacker)

- [ ] Similar to the Alliance commander, Commander Dardosh is always present inside the fort, regardless of who controls it, and is missing from the graveyard when Alliance controls it. 

Both versions of the quest Slay them All that he offers should be mutually exclusive:
https://www.wow-mania.com/armory/?quest=13178 (Defender)
https://www.wow-mania.com/armory/?quest=13180 (Attacker)

- [ ] While Lieutenant Murp offers the correct version of Stop/Defend the Siege whether Horde controls wg or not, it should be possible to complete any version of the quest that was previously taken, at either version of the NPC. This behavior works fine with Senior Demolisher Legoso for alliance. Each instance of the NPC should only offer one quest (works fine), but should reward either version, had the player completed it.

**Comment by Rushor** [comment]
added the exclusivity for all the quests

**Comment by Oganku** [comment]
Alliance can still get both versions of the same quests (attacker and defender) in the same week. Other conditions might still happen.

**Comment by Rushor** [comment]
All quests are affected?

**Comment by Oganku** [comment]
The 4 elemental ones for alliance. 

 A Rare Herb
https://www.wow-mania.com/armory/?quest=13156 (Defender)
https://www.wow-mania.com/armory/?quest=13195 (Attacker)

 Bones and Arrows
https://www.wow-mania.com/armory/?quest=13154 (Defender)
https://www.wow-mania.com/armory/?quest=13196 (Attacker)

The defender version of Fueling the Demolishers (Alliance), is missing from Siege Master Stouthandle when Alliance holds the fortress. Horde do have access to both their versions however. Need to also make sure both versions are exclusive to each other.

 Fueling the Demolishers
https://www.wow-mania.com/armory/?quest=236 (Defender)
https://www.wow-mania.com/armory/?quest=13197 (Attacker)

 Warding the Warriors
https://www.wow-mania.com/armory/?quest=13153 (Defender)
https://www.wow-mania.com/armory/?quest=13198 (Attacker)

**Comment by wow-mania** [comment]
Can we make sure we close this once for all. I will make it priority high. When we close it I will not allow it to re-open this time.

**Comment by Rushor** [comment]
can you test this again pls? i cannot take the other quest if i already took one https://i.imgur.com/ZeZTm62.jpeg

**Comment by Rushor** [comment]
> The defender version of Fueling the Demolishers (Alliance), is missing from Siege Master Stouthandle when Alliance holds the fortress. 

should be fixed now

**Comment by Rushor** [comment]
The other issues must be stay as-is for now

just check if we can take the important quests depending on state of the keeper of WG

**Comment by Oganku** [comment]
- Commanders properly despawn when the faction that holds wintergrasp switches.

- All quests are available at the correct NPCs and none block others that they shouldn't.

- The correct exclusivity for attacker/defender is present.

Only 2 points I could still find are:

- [ ] Lieutenant Vieron Blazefeather shows a ! in both attacker and defender locations, but does not offer either of Bones and Arrows. You can see he has the quests, but players aren't able to receive them.

https://www.wow-mania.com/armory/?quest=13193 (Defender) 
https://www.wow-mania.com/armory/?quest=13199 (Attacker)

- [ ] The Attacker/Defender versions of quests can currently only be turned in to the corresponding attacker/defender NPC. Technically if you complete either quest, you should be able to turn it in to either version of the NPCs. It's not *too* bad, but if we wanna fully fix it before closing it for good, this should be addressed.

**Comment by Rushor** [comment]
> Lieutenant Vieron Blazefeather shows a ! in both attacker and defender locations, but does not offer either of Bones and Arrows. You can see he has the quests, but players aren't able to receive them.

this should work now

**Comment by jeyrella** [comment]
This has, once again become bugged.  This has been working absolutely fine for months, now all of a sudden it's messed up again, and causing real problems for the WG weekly quests.  Some regression here at play:

Redemption WG when Ally have the fort
![image](https://user-images.githubusercontent.com/46089380/152896800-a850c462-24d1-4350-8078-fe8acf17e095.png)
![image](https://user-images.githubusercontent.com/46089380/152896823-9fe83fcf-6580-4e81-89da-7a036f41729e.png)
2x Molforts visible
![image](https://user-images.githubusercontent.com/46089380/152896874-dd81d5c5-7181-4025-92e9-6b3837d84188.png)
![image](https://user-images.githubusercontent.com/46089380/152896886-0e5381a3-de70-4dc1-aa25-e4f9c31c7548.png)

on PTR:
![image](https://user-images.githubusercontent.com/46089380/152896911-dbfc2760-477f-45f9-b87b-75d3a30d40cc.png)


Questgivers and questions should NOT be available if opposite faction holds the fort.

**Comment by Echinaceax** [comment]
### Tested again now Horde has the Fort 

- [ ] What i see is npcs in the fort ally and horde 
- [ ] While horde have the fort there are 2 spawns of each npc, spawned in fort (for winners) and at the flight path 
- [ ] Cant deliver quest back, coz npcs all messed up 

shouldnt be here when horde have the fort / or vice versa

![horde have the fort](https://user-images.githubusercontent.com/39439201/152978589-572f73ff-cd18-4142-b230-26e8f72ad435.jpg)

Still Some Ally npcs in fort after horde win (not sure if they are meant to be) ? 
![ALLY](https://user-images.githubusercontent.com/39439201/152979462-c33ca989-3e2d-401e-9055-3d3dfa0d3b87.jpg)

cant hand quest back (not at either spawns) 
 
![horde have the fort3](https://user-images.githubusercontent.com/39439201/152979740-f23e0315-09a0-4aef-8898-93e5a064471f.jpg)

**Comment by Rushor** [comment]
not really a regression, it was some new (wrong) npcs beeing spawned. not sure why, but it's fixed now.

**Comment by Echinaceax** [comment]
> not really a regression, it was some new (wrong) npcs beeing spawned. not sure why, but it's fixed now.

will check fix tomorrow when PTR up 😄 👍

**Comment by Rushor** [comment]
fixed, there are always 2 kind of quests, the defender and the attacker version. the defender quest version can only be rewarded in the defender camp, the attacker version only in the attacker camp, that's the only working way we can handle those quests

https://i.imgur.com/4Qk6Sh9.jpeg
https://i.imgur.com/lLoYwV1.jpeg

**Comment by Rushor** [comment]
and the ones in fort: 
https://i.imgur.com/OtjPPV9.jpeg
https://i.imgur.com/7jkWr9K.jpeg

So if you wanna take the defender quest version and reward it in the fort it will not work and vise versa

**Comment by Echinaceax** [comment]
perfect, All looks good @Rushor 

Tested both fort quest pickups and Base quest pickups / quest deliveries ✅ 
Also tested "Victory in Wintergrasp" picked up from Base, win battle and delivered at fort ✅ 

![picked up at base delivered at fort working](https://user-images.githubusercontent.com/39439201/153202074-a8b9a6c6-1857-443b-a801-b004774d8b3d.jpg)
