### ISSUE TITLE
[Item/Proc] Solace of the Defeated/Fallen

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4944]
**Links:** https://www.wow-mania.com/armory/?item=47041
https://www.wow-mania.com/armory/?item=47271
https://www.wow-mania.com/armory/?item=47059
https://www.wow-mania.com/armory/?item=47432

https://www.wow-mania.com/armory/?spell=67750
https://www.wow-mania.com/armory/?spell=67696

**What is Happening:** The Energized [(1](https://www.wow-mania.com/armory/?spell=67696)/[2](https://www.wow-mania.com/armory/?spell=67750)) proc does not proc from all sources that should proc it. 

**What Should happen:** Energized effect from the 4 different versions of the Solace trinkets should be applied whenever a spell of ANY kind is cast. Whether it be a harmful or helpful spell, or even a utility one. Each instance of a spell should proc one individual stack of energized. Skimming through wowhead comments shows such examples:

> Resto Druids:
You get 5 (6 with glyph) stacks of this buff when you cast Wild Growth.

> When you cast a raid buff the stack goes to 8 automatically...i throw out a buff before the raid just to get my mp5 from the start.

>  Circle of Healing and Holy Nova now add stacks equal to the number of targets they hit! So one CoH in a raid = 6 stacks!

> Procs 5 times for dropping 4 totems.
Also procs for lifting totems.

HoT and DoT ticks should NOT grant stacks, while the initial casts of either will grant stacks. Penance should grant stacks for each individual "ball" that hits.

This issue is quite insignificant in PvE, but matters a fair bit in PvP since it's harder to build and maintain full stacks of Energized.

**Comment by bLeyaa** [comment]
Just to add, HoT / DoT rule should also apply for shaman shields.

**Comment by Keader** [comment]
fixed but... what is the source of those comments?

**Comment by bLeyaa** [comment]
It's wowhead

**Comment by Oganku** [comment]
Much better overall. Only issue I still encountered is:

- [ ] AoE heals such from [Holy Nova](https://www.wow-mania.com/armory/?spell=48078) don't grant stacks for friendly targets hit, only for hostile ones. Oddly enough, [Circle of Healing](https://www.wow-mania.com/armory/?spell=48089) worked perfectly. 

Great job overall on the change. 👍

**Comment by Keader** [comment]
fixed
