### ISSUE TITLE
Spire Frostwyrm weird positioning

### ISSUE THREAD

**Issue by jonathan5er** [WoWManiaUK/Redemption#5191]
**Links:** http://www.wow-mania.com/armory?npc=37230

**What is Happening:** This dragon that activates on the way to Gunship Battle is having really weird positioning... he will fly up random in air and as melee cannot hit him at all... if people taunt he come down for short time and then goes in weird position in air again

**What Should happen:** This dragon should be on ground entire time (need cut his wings :D)

**Comment by Rushor** [comment]
oh sorry - missklicked

**Comment by Rushor** [comment]
https://i.imgur.com/EbfAPL0.png

the frostwyrm will no only trigger and spawn and attack if you walk over the platform (no longer in random LOS locations)

**Comment by jonathan5er** [comment]
@Rushor Is this one before turning to ship? because there is one more dragon i think when go for giant for weekly quest and this look like second on picture

**Comment by Rushor** [comment]
yes both are fixed - you can lo longer trigger them in strange position, only on the ramparts of skull platforms

**Comment by jonathan5er** [comment]
Hello @Rushor this still happen with Spire Frostwyrm... when in combat instead of stay on ground it fly up little above ground so melee cannot damage and just stay there

**Comment by Oganku** [comment]
Is still happening and that wyrm is going haywire walking midair, standing over people and not respecting any kind of gravity.

**Comment by Rushor** [comment]
issue is: we have no option to change gravity (it is all only visual) Big issue in general. I can work on a solution in general bt that would require a new ticket since it needs a bigger implemenatation.

For now i added: The npc becomes visually grounded as soon as he deals damage. So i delayed his range attacks

**Comment by Oganku** [comment]
Looks fine now, tried to drag it over collisions to make it go up but it wouldn't.
