### ISSUE TITLE
[Item] Scintillating Mana Ray - typo in name and item

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5289]
**Links:**
https://wow-mania.com/armory/?item=150563
https://wow-mania.com/armory/?spell=150290

**What is Happening:**
Has leading line break in item/spell name.

![image](https://user-images.githubusercontent.com/46089380/107120310-d85edf00-6884-11eb-8276-f02d16cae4eb.png)
![image](https://user-images.githubusercontent.com/46089380/107120329-fa586180-6884-11eb-8185-aa311e81116d.png)

see blank line at top (compared to 
![image](https://user-images.githubusercontent.com/46089380/107120352-0d6b3180-6885-11eb-970b-145c3d106118.png))

Means mount also shows at the start of the mount page, instead of alphebetized under "S"

**What Should happen:**
Should have no leading line break in name

**Comment by Keader** [comment]
Item name i fixed.
But spell name, only @wow-mania can fix

**Comment by wow-mania** [comment]
That is done already.

**Comment by jeyrella** [comment]
Still not quite right in mounts list.  Talking to janitor about it.

**Comment by Keader** [comment]
mount  is part of spell/spell description
