### ISSUE TITLE
[NPC] Library Guardian is stuck inside terrain - Storm Peaks

### ISSUE THREAD

**Issue by Anirsb** [WoWManiaUK/Redemption#5310]
**Links:**

**What is Happening:**
One of the "library Guardian" in the storm peaks, the trash where the Jeeves schematic drops, its stuck inside a wall out of sight, can't pull him, can't kill him, 
i know been farming this schematic for weeks few hours almost everyday, and it never drops, i suspect this stuck  guy to be the reason it never drops.

![thumbnail_20210215_110209](https://user-images.githubusercontent.com/63448040/107932618-0e374e00-6f7e-11eb-8cb9-ba1ecb1fbe13.jpg)

**Comment by Rushor** [comment]
can you show me where on worldmap it is, so i can better find the position

**Comment by Anirsb** [comment]
sure there it is
![WoWScrnShot_021521_112656](https://user-images.githubusercontent.com/63448040/107934768-c1a14200-6f80-11eb-8ca4-e8bde81805b9.jpg)

**Comment by Anirsb** [comment]
i'm standing by right now

**Comment by jeyrella** [comment]
Confirmed
![image](https://user-images.githubusercontent.com/46089380/107947701-a804f800-6f8a-11eb-9387-f05ccfc4c96d.png)

NPC currently selected by player:
DB GUID: 98420, current GUID: 1016.
Faction: 14.
npcFlags: 0.
Entry: 29724.
DisplayID: 26476 (Native: 26476).
Level: 78.
EquipmentId: 1 (Original: 1).
Health (base): 11770. (max): 11770. (current): 11770.
InhabitType: 3
Unit Flags: 134217728
UNIT_FLAG_MOUNT (0x8000000)
Unit Flags 2: 2048.
Dynamic Flags: 0.
Faction Template: 14.
SpawnTime: Full:5m Remaining:0s
Loot: 29724 Pickpocket: 0 Skinning: 29724
InstanceID: 0
Phasemask: 1
Armor: 9104
Position: 8319.950195 -950.624023 923.956970.
AIName: SmartAI ScriptName: 
Flags Extra: 0
MechanicImmuneMask: 0

**Comment by jeyrella** [comment]
very hard to figure out from wowhead where exactly it should be instead, but i suggest somewhere around this empty spot here
![image](https://user-images.githubusercontent.com/46089380/107948055-3aa59700-6f8b-11eb-92a3-8d6729792096.png)

**Comment by Anirsb** [comment]
anywhere we can actually kill it would be good :) 
has it been fixed ?

**Comment by jeyrella** [comment]
No, it will only be fixed on Redemption once you see it updated in the wow-mania Changelog on Discord.  All development is done on our Test Realm first.

**Comment by Rushor** [comment]
position adjusted

**Comment by jeyrella** [comment]
Fixed
![Uploading image.png…]()

**Comment by Anirsb** [comment]
not fixed 
![WoWScrnShot_021721_173829](https://user-images.githubusercontent.com/63448040/108236300-0a0a5c80-7147-11eb-97d5-86054f3650ca.jpg)
![WoWScrnShot_021721_173834](https://user-images.githubusercontent.com/63448040/108236309-0bd42000-7147-11eb-9ec2-8d176e9733e5.jpg)

**Comment by jeyrella** [comment]
@Anirsb as i said earlier, it is first fixed on PTR before moving to Redemption https://github.com/WoWManiaUK/Redemption/issues/5310#issuecomment-779393714

That's why the label says "Fixed in PTR"
