### ISSUE TITLE
[SPELL] Intercept

### ISSUE THREAD

**Issue by KyptAMaN** [WoWManiaUK/Redemption#5473]
**Links:**https://www.wow-mania.com/armory/?spell=20252

**What is Happening:**
This is the last time i report this stupid bug.
Ok so intercept is getting parried/dodged by players when the stun it self cant be countered with rng parry or dodge. only way to avoid intercept STUN is with a counter spell, (ex: icebound fortitude on dks, deterrence hunters, etc..) other than that u cant avoid the stun, the only thing u can parry/dodge is the dmg of it wich is useless to be honest since is so low but its the only thing u can dodge/parry on intercept.
But still.. u guys have to fix this, warrior without stuns at pvp is useless and pointless.
Right now, hunters/ferals and rogues are unstunable , please do ya job and fix this, its sad.
Also, Charge getting interrupted by pets stuns and frost mages freezes etc.. , so u cant reach the enemy how u should.. u could also look into charge aswell .  Ty

**What Should happen:**
Intercept should never get parried or dodged without a counter for it.
Only the dmg of intercept can be dodged/parried, NOT the STUN.
 
 Ty for your attention and please fix this, its a shame.

**Comment by KyptAMaN** [comment]
Sure since its been 2 years with this bug, and i already reported like 3 times and no 1 gives a damn. ;)
Also, check charge aswell .
I wouldnt report it if i didnt care about server, trying to help .

**Comment by Keader** [comment]
fixed.

**Comment by GMZinius** [comment]
@Keader 
I see that your fix was'nt confirmed by a tester 
The player is reporting that this is still not fixed 
parry/dodge is the issue player is reporting 

Can you look into this again please, Thanks 

side note
Execute 0 dmg and Heroic Throw has issues in PvP player also mentioned

**Comment by Keader** [comment]
try now please on ptr

**Comment by KyptAMaN** [comment]
Not fixed yet, still getting dodged/parried , when its IMPOSSIBLE to dodge/parry the stun, only way to avoid is with some immune to stuns spells, like deterrence, Icebound fortitude.. other than that, u cant avoid the intercept STUN .

**Comment by Keader** [comment]
> Not fixed yet, still getting dodged/parried , when its IMPOSSIBLE to dodge/parry the stun, only way to avoid is with some immune to stuns spells, like deterrence, Icebound fortitude.. other than that, u cant avoid the intercept STUN .

i need reproduce steps
I tested in ptr with 90% dodge/parry chance and it still hit

**Comment by KyptAMaN** [comment]
it seems fixed, damn, finally...  gj!

**Comment by GMZinius** [comment]
> it seems fixed, damn, finally... gj!

Thank you for confirming fixed on live realm 👍
