### ISSUE TITLE
[Quest] Kaw the Mammoth Destroyer

### ISSUE THREAD

**Issue by Wolch** [WoWManiaUK/Redemption#5550]
**Links:**
www.wowhead.com/quest=11879

**What is Happening:**
Kaw is missing. His mammoth is there, but Kaw himself does not spawn even if I attack the mammoth or even kill it. 

**What Should happen:**
Kaw must jump on his mammoth when it is attacked

**Comment by Rushor** [comment]
just wait a few minutes until he respawn, then try the quest again :)

**Comment by Wolch** [comment]
I have waited more than 10 mins, killed the mount twice. Kaw didn't spawn, I opened an in-game ticket, Psygoa came and confirmed that this is a bug and asked me to report it here.

**Comment by Echinaceax** [comment]
Confirmed bug by Zinius to now

Re-opening this

**Comment by Echinaceax** [comment]
Gms are still getting regular ingame tickets about this @Rushor 

Seems this fix #5016 didnt fix it 

Can you look into this again please

me and maine will try and find out the reason why it bugs

**Comment by Lumber-Jack-2** [comment]
so the both creatures are not there at the same time? a clear reproduce would be great here. okay i will wait :)

**Comment by Echinaceax** [comment]
> so the both creatures are not there at the same time? a clear reproduce would be great here. okay i will wait :)

Yes seems to work fine. 
Still trying to get it to bug lol 

more time needed :)

**Comment by fvicaria** [comment]
This has been working. I don't understand why re-open.

**Comment by Echinaceax** [comment]
> This has been working. I don't understand why re-open.

Ive sent you a private message @fvicaria :)

**Comment by Maine1** [comment]
Ok, I have the reproduce -
If players kill it too quickly without using a mammoth bull to kill it he doesn't mount on it and just becomes available to kill. 

Where the issue is - Players can kill it too quick and make Kaw the Mammoth Destroyer disappear instead of becoming available to fight. I have a video of the reproduce. 
https://mega.nz/file/VmZFwIwY#zar0pElWbJ3M96sYzju3eZ-PFSoY0GePcf2kGelcKHo Timestamp - 1:05

@Rushor remember the fix for Karazhan horse boss. You set a cap on health so they couldn't kill the horse before Attumen the Huntsman mounted the horse. Can you do the same thing for this NPC (Moria) To set a cap of health to allow Kaw the Mammoth Destroyer to mount Moria before they can kill it

**Comment by Lumber-Jack-2** [comment]
can add setting invincible hp yeah

**Comment by Lumber-Jack-2** [comment]
moira will be stuck at 10 percent hp now (pls test only with normal dmg spells), then kraw will mount and once he is mounted her hp will go up to full heal again and is unstuck and killable again

stuck, here means that she cannot drop below 10 percent hp value

**Comment by Maine1** [comment]
Tested but can still drop to 1 HP and it gets stuck and kaw does not mount the mammoth 
@Rushor 
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/9d2bc7dc-5c3e-405a-8c7e-307584294ee5)

**Comment by Lumber-Jack-2** [comment]
okay new change. moira will have 180.000 hp on start (i dont think any player can do that much dmg)
then once kraw mounts her, she will drop down to 5 percent of 180.000 hp, which is her basehp again. normal fight can continue

**Comment by Maine1** [comment]
Using Wooly Mammoth Bull to kill him doesn't work the mammoth gets stuck at 1.1% hp.
Using your own spells you can kill the mammoth without him jumping on it.
Upon respawn Kaw the Mammoth Destroyer doesn't respawn.

**Comment by Maine1** [comment]
Ok, @Rushor all tested and seems to be working well.
Last thing to fix is the fear on Kaw the Mammoth Destroyer from the Wooly Mammoth Bull




- [ ] Kaw the mammoth destroyer is supposed to be immune to Wooly Mammoth Bull fear
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/1c820b47-e068-431e-a3d9-760c2feb51e7)
Spell name - Thundering Roar
Spell ID - 46316

**Comment by Lumber-Jack-2** [comment]
added that

**Comment by Echinaceax** [comment]
Confirmed all fixed in PTR 
thanks @Rushor ❤️

**Comment by Maine1** [comment]
Still not working correctly over on live.
Kaw the Mammoth Destroyer still disappears sometimes too

**Comment by Lumber-Jack-2** [comment]
well nothing more that can be done there - applied the fix again to make sure the hp values are correct on spawn

**Comment by Echinaceax** [comment]
hopefully with the hp fix it cant bug for killing to fast @Rushor 
GMs will let us know. thanks
