### ISSUE TITLE
[Spell] Ghoul's Touch does not stack

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5655]
**Links:** https://www.wow-mania.com/armory/?spell=70782

**What is Happening:** The [Ghoul's Touch](https://www.wow-mania.com/armory/?spell=70782) debuff applied by the ghouls in Frostmourne Cavern currently does not stack.

**What Should happen:** As the tooltip implies, it should be able to stack up to 4 times.

**Comment by Rushor** [comment]
fixed after next compile

**Comment by jeyrella** [comment]
well apparently ptr was recompiled, and it still isn't stacking
![image](https://user-images.githubusercontent.com/46089380/147113989-1a240271-e9a2-4d1f-ab5e-e7022c7a4e8d.png)

**Comment by Rushor** [comment]
had to rescript that spell, the enemy will apply the debuff every 5 seconds now (this enables stacking). Debuff will last 5 seconds. So it will be removed again once the ghouls close are all dead. Only option we have here. added that

**Comment by jeyrella** [comment]
fixed, works well
![image](https://user-images.githubusercontent.com/46089380/147139692-ce957a39-7074-406f-9836-805e01f67f01.png)
