### ISSUE TITLE
[Item/Spell] Althor's Abacus should proc from Glyph - PW:S

### ISSUE THREAD

**Issue by hawker357** [WoWManiaUK/Redemption#5675]
**Links:**
https://www.wow-mania.com/armory/?item=50366 (HC Abacus)
https://www.wow-mania.com/armory/?item=50359 (NM Abacus)
https://www.wow-mania.com/armory/?spell=71642 (HC Proc Spell)
https://www.wow-mania.com/armory/?spell=71611 (NM Proc Spell)
https://www.wow-mania.com/armory/?spell=56175 (Glyph PW:S Spell)
https://www.wowhead.com/item=50359/althors-abacus#comments

**What is Happening:**
Abacus proc does not trigger from PW:S Glyph spell. Have tested by unequipping/equipping armor (not trink so the ICD doesn't reset), over 20 heals from the Glyph and no proc, also looked at 25HC boss fight data where my only heals were PW:S / Glyph PW:S / Prayer of Mending, multiple (20+) heals did not trigger Echoes of Light.

**What Should happen:**
The Proc (Echoes of Light) should trigger when a player is healed by the Glyph of PW:S.

**Comment by Keader** [comment]
fixed

**Comment by Oganku** [comment]
Thanks for the clear report btw. Fix works well for hc trinket, but still doesn't proc for the nm version.
Item 50399 | Proc 71611
