### ISSUE TITLE
[NPC] Zandras missing / incorrect spawn timer - SMV

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5754]
**Links:**
Zandras: https://www.wow-mania.com/armory/?npc=21827
Needed for Quest: https://www.wow-mania.com/armory/?quest=10622
Illidari Agonizer: https://www.wow-mania.com/armory/?npc=19801

**What is Happening:**
Zandras is not respawning. I am sure I have done this quest without problem about a year ago, maybe more. But today I couldn't find the NPC and one or two people are looking for it past three days if not more. I think there is something wrong with respawn timer.
There is only one Ilidari Agonizer respwning on the walls and he stands still on spot. Two Agonizer should follow him around the walls.

**What Should happen:**
Zandras should have a longer respawn timer but it should be about 10-15 minutes not days.
Here: https://tbc.wowhead.com/quest=10622/proof-of-allegiance#comments (comment by 52276)

**Comment by jeyrella** [comment]
High:  If valid, locks out the following long quest chains, including BT attunement and SMV quest achievement.

**Comment by Echinaceax** [comment]
Had a GM check for me just now, and he is spawned,  and a 5 min timer check too @Greywolf59

**Comment by Rushor** [comment]
can confirm he is in db guid is: 76415

will check other things that may make him despawn / invis or sth else

**Comment by Greywolf59** [comment]
I have logged in jsut now and he is nowhere to be found. Naxxramas realm.

**Comment by Echinaceax** [comment]
Well that info helps a lot more @Greywolf59 
didnt see you mean Naxx

**Comment by Greywolf59** [comment]
Yeah I play on Naxx now a lot, thus I started noticing the Outland stuff, thus the github posts :)

**Comment by Echinaceax** [comment]
> Yeah I play on Naxx now a lot, thus I started noticing the Outland stuff, thus the github posts :)

Wait, All your recent reports are all for naxx realm too ?

**Comment by Greywolf59** [comment]
I thought they share the same core. What is broken on Red is broken on Naxx. What gets fixed on Red gets fixed on Naxx.
???

**Comment by Echinaceax** [comment]
> I thought they share the same core. What is broken on Red is broken on Naxx. What gets fixed on Red gets fixed on Naxx. ??? And yes, all my reports from Outland are from Naxx realm.

All good had a chat with Jeyrella 😄

**Comment by jeyrella** [comment]
Hidden comments as outdated to prevent confusion, yes there is a shared code.  We just need to test this specific issue, is all.

**Comment by Echinaceax** [comment]
Checked Issue on RED (with and without quest) respawn is fine @Rushor 
GM checked Naxx and seens only Naxx has issue

**Comment by Greywolf59** [comment]
I was thinking maybe restart of Naxx might help? It never crashed and I haven't noticed it being restarted anytime the Red was? Might respawn Zandras if he bugged somehow under textures or something.

**Comment by Echinaceax** [comment]
update:

Fixed after server restart this on Naxx 
will close this issue now thanks @Greywolf59

**Comment by Greywolf59** [comment]
I hope you still get notif even if it is closed. Zandras ia missing again. I have checked only now. It seems like there is reoccuring problem with his respawn after death on Naxx realm.

**Comment by Echinaceax** [comment]
Thanks @Greywolf59 will check
