### ISSUE TITLE
[Quest] The Hunter and the Prince - Fall through texture on use of Annihilate vehicle spell

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5837]
**Links:**
Quest 13400  https://www.wowhead.com/quest=13400/the-hunter-and-the-prince#comments
Spell 60642   https://www.wowhead.com/spell=60642/annihilate

**What is Happening:**
On use of the Annihilate spell (13400, number 4 on the Prince Arthas Menethil vehicle), player falls through the floor texture into abyss.
Seen on both Redemption live and on PTR
https://youtu.be/Rzox2bks2o4

**What Should happen:**
Player shouldn't fall through the floor texture

**Comment by jeyrella** [comment]
Yes, I have done it before myself, on several toons.  Now, it is completely broken, you can't do it without using that skill, and as soon as you do you fall through the floor and die.

**Comment by mfranca0009** [comment]
Fixed.
https://i.gyazo.com/3b9ec0e07b1a1d0a3a17d4f69a8a9ce6.mp4

**Comment by Echinaceax** [comment]
https://i.gyazo.com/99241a357b55db44267b8046b1e8d4c0.mp4

**Comment by mfranca0009** [comment]
Yes, and this isn't a problem with the recent update. This is a problem with vmaps/mmaps and the fact that if you use `stomp` and he gets thrown to the angled terrain that is behind where he initially spawns he will clip through the ground like he got thrown back on the even part of the terrain.

Jumping on him when he's clipping through the ground causes the player to fall through. NPCs clipping through the ground isn't a new occurrence it's been like this.

**Comment by Echinaceax** [comment]
confirmed via my own test as franca has stated 

happened when Illidan is clipping the ground, player falls through 

https://i.gyazo.com/99241a357b55db44267b8046b1e8d4c0.mp4

![image](https://user-images.githubusercontent.com/39439201/170586042-fccd618b-54b2-47b3-9e9a-54771ce9fb65.png)

**Comment by Keader** [comment]
try now please

**Comment by Echinaceax** [comment]
Confirmed fixed in PTR  

The stomp doesnt throw him so far now, 

note: hard though to get the Annihilate combo but i think its fine 
could complete it with no issue 

https://i.gyazo.com/caba58623ddbb6564a8d756a53ece9e5.mp4

**Comment by mfranca0009** [comment]
Not fixed.

Video: https://i.gyazo.com/24ffc073157404e4da19ecc9e3de10c8.mp4

Recorded about 1 minute ago, and if you bring him to an uneven surface, use `stomp`, then quickly use `Annihilate`, it will still throw the player underneath the map because Illidan is still clipping through the ground.

The uneven surface I am talking about for reference:
![image](https://user-images.githubusercontent.com/26092980/174510666-c7e26710-0119-4b9d-abbb-80ef185a2f57.png)

**Comment by Keader** [comment]
I consider this fixed since you can do quest without any problem.
How many players will try go to this exactly spot that can cause issues?
Important part here is fixed, but yest, it's a specific case, we need a general fix for this in future.
