### ISSUE TITLE
[Spell] Mage T10 2P Bonus

### ISSUE THREAD

**Issue by custos77** [WoWManiaUK/Redemption#599]
A few days ago the set bonus was working fine. Using "Pyroblast!" after hot streak would give me a buff of 12% haste for 4-5 seconds. Called "Pushing the Limit" I think.

Now it doesn't work. I tried removing the transmogrification but that didn't change anything. The item levels I'm using are 264 and 251. I know that's supposed to trigger the set bonus, but in case that's related to the bug maybe it helps.

This is not a very small dps loss so I hope it's fixable.

Thanks for your work all the time

**Comment by fvicaria** [comment]
Should be fixed in dev today and in prod tomorrow.

**Comment by philoudu16** [comment]
The 2P set bonus still doesn't seem to be fixed (at least with missile barrage and hot streak procs).

**Comment by custos77** [comment]
In case it helps, seen "Pushing the Limit" proc once out of using 100+ hot streaks. Not sure how it worked that time. So it almost never works but not never.

**Comment by fvicaria** [comment]
Reopening to investigate.

**Comment by custos77** [comment]
Any estimation when the update is pushed?
